#ifndef REMAP_H
#define REMAP_H

#define NIMBOS_BASE_PADDR 0x42000000
#define NIMBOS_SIZE 0x8000000
#define NIMBOS_END_PADDR NIMBOS_BASE_PADDR + NIMBOS_SIZE

#define NIMBOS_KERNEL_BASE_PADDR NIMBOS_BASE_PADDR
#define NIMBOS_KERNEL_MAXSIZE 0x8000000

#define NIMBOS_KVADDR_OFFSET 0xFFFFFF8000000000
#define SHADOW_KVADDR_OFFSET -0x2A000000

#define NIMBOS_USER_STACK_SIZE 4096 * 4 // 16K
#define NIMBOS_USER_STACK_TOP_VADDR 0x10000000
#define NIMBOS_USER_STACK_BASE_VADDR NIMBOS_USER_STACK_TOP_VADDR - NIMBOS_USER_STACK_SIZE


#define NIMBOS_KERNEL_PADDR_TO_VADDR(phy_addr) (NIMBOS_KVADDR_OFFSET + phy_addr)
#define NIMBOS_KERNEL_VADDR_TO_PADDR(virt_addr) (virt_addr - NIMBOS_KVADDR_OFFSET)

#define SHADOW_KERNEL_PADDR_TO_VADDR(phy_addr) (SHADOW_KVADDR_OFFSET + phy_addr)
#define SHADOW_KERNEL_VADDR_TO_PADDR(virt_addr) (virt_addr - SHADOW_KVADDR_OFFSET)

#define NIMBOS_KERNEL_BASE_VADDR NIMBOS_KERNEL_PADDR_TO_VADDR(NIMBOS_KERNEL_BASE_PADDR)


#endif // REMAP_H